services:
  nostr-caldav:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5232:5232"
    volumes:
      - ./config.yaml:/data/config.yaml:ro
      - ./data:/data
    networks:
      - default
      - noas
    restart: unless-stopped

networks:
  noas:
    external: true
